apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 214067368354.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 214067368354.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- flask-deployment-patch.yaml
- flask-service-patch.yaml
- front-deployment-patch.yaml
- front-service-patch.yaml
